
import type { Post } from '@/lib/posts';
import { formatContentForDisplay } from '@/lib/posts';
import { useEffect, useState } from 'react';

interface BlogPostViewProps {
  post: Post;
}

export function BlogPostView({ post }: BlogPostViewProps) {
  // To avoid hydration mismatch with server-rendered HTML if marked runs differently
  // or if there are client-side only aspects to its output based on environment.
  // For basic markdown to HTML, this might be overly cautious but safe.
  const [formattedContent, setFormattedContent] = useState('');

  useEffect(() => {
    setFormattedContent(formatContentForDisplay(post.content));
  }, [post.content]);

  return (
    <article className="prose prose-lg dark:prose-invert max-w-none mx-auto py-8 px-4 md:px-6">
      <header className="mb-8">
        <h1 className="text-4xl font-bold tracking-tight text-foreground md:text-5xl">{post.title}</h1>
        <p className="mt-2 text-lg text-muted-foreground">
          Published on {new Date(post.createdAt).toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
          })}
        </p>
      </header>
      {/* Ensure prose styles correctly apply to content generated by 'marked' */}
      <div 
        className="text-foreground" // Basic text color, prose styles should handle the rest
        dangerouslySetInnerHTML={{ __html: formattedContent }} 
      />
    </article>
  );
}
