
'use client'; // Add this directive

import type { Post } from '@/lib/posts';
import { formatContentForDisplay } from '@/lib/posts';
import { useEffect, useState } from 'react';

interface BlogPostViewProps {
  post: Post;
}

export function BlogPostView({ post }: BlogPostViewProps) {
  const [formattedContent, setFormattedContent] = useState('');

  useEffect(() => {
    // Ensure formatContentForDisplay is safe and doesn't cause hydration issues itself
    // For now, assuming it's okay.
    setFormattedContent(formatContentForDisplay(post.content));
  }, [post.content]);

  return (
    <article className="prose prose-lg dark:prose-invert max-w-none mx-auto py-8 px-4 md:px-6">
      <header className="mb-8">
        <h1 className="text-4xl font-bold tracking-tight text-foreground md:text-5xl">{post.title}</h1>
        <p className="mt-2 text-lg text-muted-foreground">
          Published on {new Date(post.createdAt).toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
          })}
        </p>
      </header>
      {/* 
        The 'prose' classes on the parent 'article' element will style the HTML 
        generated by 'marked'. We no longer need specific text color classes here.
      */}
      <div
        dangerouslySetInnerHTML={{ __html: formattedContent }}
      />
    </article>
  );
}
